import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { GENERATED_HEAD_LINES, generatedMarker, readHead } from "../src/generated.ts";

test("generatedMarker finds the common declarations in the head and quotes the line", () => {
  assert.equal(generatedMarker("// @generated by protoc-gen-ts\nexport const x = 1;"), "// @generated by protoc-gen-ts");
  assert.equal(generatedMarker("# Code generated by openapi-generator. DO NOT EDIT.\n"), "# Code generated by openapi-generator. DO NOT EDIT.");
  assert.equal(generatedMarker("/* This file is generated. */"), "/* This file is generated. */");
  assert.equal(generatedMarker("// autogenerated\n"), "// autogenerated");
  assert.equal(generatedMarker("export function generate() {}\n// do not edit lightly"), null, "prose is not a marker");
  assert.equal(generatedMarker(""), null);
});

test("only the head is consulted", () => {
  const late = `${"// fine\n".repeat(GENERATED_HEAD_LINES)}// @generated`;
  assert.equal(generatedMarker(late), null);
});

test("readHead returns the first bytes and empty for a missing file", () => {
  const dir = mkdtempSync(join(tmpdir(), "yolo-gen-"));
  try {
    const p = join(dir, "a.ts");
    writeFileSync(p, `// @generated\n${"x".repeat(5000)}`);
    const head = readHead(p, 64);
    assert.equal(head.length, 64);
    assert.match(head, /@generated/);
    assert.equal(readHead(join(dir, "missing.ts")), "");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
