/**
 * Files that say they are generated.
 *
 * A checked-in bundle, protobuf/openapi output, a lockfile-adjacent codegen
 * result: editing one wastes the turn — the next build overwrites it — and
 * leaves a diff that confuses everyone who reads it. The file usually says
 * so in its first lines. This reads those lines (bounded) and finds the
 * marker; the extension asks, in the modes that ask, quoting it.
 *
 * Pure apart from readHead; the matcher is table-driven and tested without
 * a filesystem. (oh-my-pi's auto-generated-guard, as a question, not a wall.)
 */
import { closeSync, openSync, readSync } from "node:fs";

export const GENERATED_HEAD_BYTES = 1024;
export const GENERATED_HEAD_LINES = 40;

const MARKERS: RegExp[] = [
  /@generated\b/i,
  /\bDO NOT EDIT\b/,
  /\bCode generated by\b/i,
  /\b(?:auto-?generated|automatically generated|machine[- ]generated)\b/i,
  /\bThis file (?:is|was) generated\b/i,
];

/** The line that declares the file generated, trimmed and capped, or null. Only the head is consulted. */
export function generatedMarker(head: string): string | null {
  const lines = head.split(/\r?\n/).slice(0, GENERATED_HEAD_LINES);
  for (const line of lines) {
    for (const re of MARKERS) {
      if (re.test(line)) return line.trim().slice(0, 120);
    }
  }
  return null;
}

/** The first `bytes` of a file as text; "" when it cannot be read (a missing file is not generated). */
export function readHead(path: string, bytes: number = GENERATED_HEAD_BYTES): string {
  let fd: number | null = null;
  try {
    fd = openSync(path, "r");
    const buf = Buffer.alloc(bytes);
    const n = readSync(fd, buf, 0, bytes, 0);
    return buf.subarray(0, n).toString("utf8");
  } catch {
    return "";
  } finally {
    if (fd !== null) {
      try {
        closeSync(fd);
      } catch {
        // already closed
      }
    }
  }
}
